### ISSUE TITLE
VoT Integration Request 

### ISSUE THREAD

**Issue by ZmaimX** [eliranwong/toolmate#18]
Hello ! your project is just amazing ! and i keep exploring new horizon with it ! a true work of art !

I wanted to suggest an integration of VoT "Visualization-of-Thought Elicits Spatial Reasoning in Large Language Models" it would be very helpful for the project to integrate automated workflows and even execute tasks from natural commands. 

here is the necessary research paper for it ==> " https://arxiv.org/abs/2404.03622 "
one good example is this project >>>>>> " https://github.com/a-real-ai/pywinassistant "

Keep shining my friend ! @eliranwong

**Comment by eliranwong** [comment]
Thanks.  The links are helpful.  I will take a look.  Thanks.
