### ISSUE TITLE
Windows Users - Upgrade Issue - unable to run the latest code

### ISSUE THREAD

**Issue by calamity1011** [eliranwong/toolmate#35]
(freegenius) PS C:\Users\vu.anhle\Desktop\Circuitpythton\openai\Freegenius> pip install freegenius
Requirement already satisfied: freegenius in c:\users\vu.anhle\desktop\circuitpythton\openai\freegenius\freegenius\lib\site-packages (0.0.1)
Requirement already satisfied: ollama in c:\users\vu.anhle\desktop\circuitpythton\openai\freegenius\freegenius\lib\site-packages (from freegenius) (0.3.2)
Requirement already satisfied: httpx<0.28.0,>=0.27.0 in c:\users\vu.anhle\desktop\circuitpythton\openai\freegenius\freegenius\lib\site-packages (from ollama->freegenius) (0.27.2)
Requirement already satisfied: anyio in c:\users\vu.anhle\desktop\circuitpythton\openai\freegenius\freegenius\lib\site-packages (from httpx<0.28.0,>=0.27.0->ollama->freegenius) (4.4.0)
Requirement already satisfied: certifi in c:\users\vu.anhle\desktop\circuitpythton\openai\freegenius\freegenius\lib\site-packages (from httpx<0.28.0,>=0.27.0->ollama->freegenius) (2024.8.30)
Requirement already satisfied: httpcore==1.* in c:\users\vu.anhle\desktop\circuitpythton\openai\freegenius\freegenius\lib\site-packages (from httpx<0.28.0,>=0.27.0->ollama->freegenius) (1.0.5)
Requirement already satisfied: idna in c:\users\vu.anhle\desktop\circuitpythton\openai\freegenius\freegenius\lib\site-packages (from httpx<0.28.0,>=0.27.0->ollama->freegenius) (3.8)
Requirement already satisfied: sniffio in c:\users\vu.anhle\desktop\circuitpythton\openai\freegenius\freegenius\lib\site-packages (from httpx<0.28.0,>=0.27.0->ollama->freegenius) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\vu.anhle\desktop\circuitpythton\openai\freegenius\freegenius\lib\site-packages (from httpcore==1.*->httpx<0.28.0,>=0.27.0->ollama->freegenius) (0.14.0)
(freegenius) PS C:\Users\vu.anhle\Desktop\Circuitpythton\openai\Freegenius> freegenius
in progress

main.py :
def main():
    print("in progress")

**Comment by eliranwong** [comment]
Can you try to install the latest one with `pip install --upgrade freegenius==0.2.97` ?  The Windows version does not do auto-upgrade, as implemented in macOS and Linux, so you need to upgrade manually.

The code you quoted is not in my current code, so I guess it is a very very old copy:

```
main.py :
def main():
print("in progress")
```

**Comment by eliranwong** [comment]
With the latest version, you should be able to benefit from the latest feature https://github.com/eliranwong/freegenius/wiki/Multiple-Tools-in-One-Go

**Comment by calamity1011** [comment]
Thank you @eliranwong. 
It was strange for me too, since it downloaded and installed all dependencies but not the main code.
reset up the virtual environment as 3.11 but Triton package seems to be a problem for Window user.
PS C:\Users> py -3.11 -m venv freegenius
PS C:\Users\> Freegenius\Scripts\activate
(Freegenius) PS C:\Users\freegenius> pip install --upgrade freegenius==0.2.97
Collecting freegenius==0.2.97
  Using cached freegenius-0.2.97-py3-none-any.whl.metadata (18 kB)
Collecting llama-cpp-python==0.2.81 (from llama-cpp-python[server]==0.2.81->freegenius==0.2.97)
  Using cached llama_cpp_python-0.2.81.tar.gz (50.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
INFO: pip is looking at multiple versions of freegenius to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement triton==2.3.0 (from freegenius) (from versions: none)
ERROR: No matching distribution found for triton==2.3.0

**Comment by eliranwong** [comment]
> Thank you @eliranwong. It was strange for me too, since it downloaded and installed all dependencies but not the main code. reset up the virtual environment as 3.11 but Triton package seems to be a problem for Window user. PS C:\Users> py -3.11 -m venv freegenius PS C:\Users> Freegenius\Scripts\activate (Freegenius) PS C:\Users\freegenius> pip install --upgrade freegenius==0.2.97 Collecting freegenius==0.2.97 Using cached freegenius-0.2.97-py3-none-any.whl.metadata (18 kB) Collecting llama-cpp-python==0.2.81 (from llama-cpp-python[server]==0.2.81->freegenius==0.2.97) Using cached llama_cpp_python-0.2.81.tar.gz (50.4 MB) Installing build dependencies ... done Getting requirements to build wheel ... done Preparing metadata (pyproject.toml) ... done INFO: pip is looking at multiple versions of freegenius to determine which version is compatible with other requirements. This could take a while. ERROR: Could not find a version that satisfies the requirement triton==2.3.0 (from freegenius) (from versions: none) ERROR: No matching distribution found for triton==2.3.0

Thanks for information.  I will check on Windows and get back to you, possible next week.  Sorry for the issue.

**Comment by eliranwong** [comment]
@calamity1011 Please try version 0.3.14 and let me know.  I removed the "triton" from the requirements.txt

**Comment by eliranwong** [comment]
@calamity1011 I renamed the package, please kindly try and let me know, thanks:

> pip install --upgrade toolmate

**Comment by eliranwong** [comment]
I assume it is sorted.  closing this issue now.  please feel free to let me if I may help further
