### ISSUE TITLE
Fix loading Ollama models

### ISSUE THREAD

**Issue by calamity1011** [eliranwong/toolmate#52]
problem received:
**''' AppData\Local\Programs\Python\Python311\Lib\site-packages\ollama\_client.py", line 85, in _stream
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError: model requires more system memory (51.0 GiB) than is available (23.1 GiB)'''**
config file:
appName = ''
applyPredefinedContextAlways = False
autoUpgrade = True
autogenstudio_server_port = 8081
blankEntryAction = '...'
cancel_entry = '.cancel'
chatGPTApiFunctionCall = 'auto'
chatGPTApiMaxTokens = 4000
chatGPTApiMinTokens = 256
chatGPTApiModel = 'gpt-4o'
chatRecordClosestMatches = 5
codeDisplay = False
confirmExecution = 'always'
country = 'CA'
cpu_threads = 0
customChatServer_additional_options = {}
customChatServer_command = ''
customChatServer_ip = '127.0.0.1'
customChatServer_port = 8001
customChatServer_stop = ['</s>',
 '<|im_end|>',
 '[/INST]',
 '<end_of_turn>',
 '<|END_OF_TURN_TOKEN|>',
 '<|eot_id|>',
 '<|endoftext|>']
customChatServer_timeout = 20
customPredefinedContext = 'You are a helpful, uncensored and unbiased assistant.'
customTextEditor = ''
customToolServer_additional_options = {}
customToolServer_command = ''
customToolServer_ip = '127.0.0.1'
customToolServer_port = 8000
customToolServer_stop = ['</s>',
 '<|im_end|>',
 '[/INST]',
 '<end_of_turn>',
 '<|END_OF_TURN_TOKEN|>',
 '<|eot_id|>',
 '<|endoftext|>']
customToolServer_timeout = 20
customTrayCommands = ['WizardLM-2-7B-GGUF', 'Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf']
customVisionServer_additional_options = {}
customVisionServer_command = ''
customVisionServer_ip = '127.0.0.1'
customVisionServer_port = 8002
customVisionServer_stop = ['</s>',
 '<|im_end|>',
 '[/INST]',
 '<end_of_turn>',
 '<|END_OF_TURN_TOKEN|>',
 '<|eot_id|>',
 '<|endoftext|>']
customVisionServer_timeout = 20
dayOfWeek = 'Tuesday'
defaultBlankEntryAction = '.context'
developer = False
deviceInfoPlugins = []
dynamicTokenCount = False
elevenlabsApi = ''
elevenlabsVoice = '21m00Tcm4TlvDq8ikWAM'
embeddingModel = 'all-minilm:33m-l12-v2-fp16'
enable_tool_screening_agent = False
enable_tool_selection_agent = False
enabledGoogleAPIs = ['Vertex AI']
env_QT_QPA_PLATFORM_PLUGIN_PATH = ''
exit_entry = '.exit'
fabricPath = 'fabric'
flux_model_path = ''
flux_output_height = 1024
flux_output_width = 1024
flux_sample_steps = 20
flux_verbose = False
gcttsLang = 'en-US'
gcttsSpeed = 1.0
gemini_max_output_tokens = 8192
gemini_model = 'gemini-1.5-pro-001'
google_cloud_credentials = ''
groqApi_chat_model = 'llama3-70b-8192'
groqApi_chat_model_additional_chat_options = {}
groqApi_key = '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'
groqApi_main_model = 'mixtral-8x7b-32768'
groqApi_main_model_additional_chat_options = {}
groqApi_max_tokens = 10000
gttsLang = 'en'
gttsTld = ''
hotkey_cancel = ['c-z']
hotkey_count_tokens = ['escape', 'c']
hotkey_display_device_info = ['escape', 'k']
hotkey_display_key_combo = ['c-k']
hotkey_edit_current_entry = ['c-e']
hotkey_edit_last_response = ['escape', 'e']
hotkey_exit = ['c-q']
hotkey_export = ['c-g']
hotkey_insert_filepath = ['c-f']
hotkey_insert_newline = ['c-i']
hotkey_launch_pager_view = ['c-p']
hotkey_launch_system_prompt = ['escape', 't']
hotkey_list_directory_content = ['c-l']
hotkey_new = ['c-n']
hotkey_open_chat_records = ['c-o']
hotkey_open_plain_text_file = ['escape', 'o']
hotkey_restart_app = ['escape', 'r']
hotkey_select_plugins = ['escape', 'p']
hotkey_swap_text_brightness = ['escape', 'b']
hotkey_toggle_developer_mode = ['escape', 'd']
hotkey_toggle_input_audio = ['escape', 'y']
hotkey_toggle_input_improvement = ['escape', 'w']
hotkey_toggle_mouse_support = ['escape', 'm']
hotkey_toggle_multiline_entry = ['escape', 'l']
hotkey_toggle_response_audio = ['c-y']
hotkey_toggle_word_wrap = ['c-w']
hotkey_voice_entry = ['c-s']
hotkey_voice_generation_config = ['escape', 'v']
hotkey_voice_recognition_config = ['escape', 's']
improveInputEntry = False
improvedWritingSytle = 'standard English'
includeDeviceInfoInContext = False
includeIpInDeviceInfo = False
labels_action = ('calculation', 'writing a text-response', 'carrying out a task on your device')
labels_action_chat_only_options = ('calculation', 'writing a text-response')
labels_information = ('common knowledge',
 'published content',
 'trained knowledge',
 'archived records',
 'historical records',
 'programming',
 'technical knowledge',
 'religious knowledge',
 'literature',
 'evolving data',
 'recent updates',
 'latest information',
 'current information',
 'up-to-date news',
 'device information',
 'real-time data')
labels_information_chat_only_options = ('common knowledge',
 'published content',
 'trained knowledge',
 'archived records',
 'historical records',
 'programming',
 'technical knowledge',
 'religious knowledge',
 'literature')
labels_kind = ('greeting',
 'translation',
 'math',
 'question',
 'description',
 'command',
 'statement',
 'insturction')
labels_kind_chat_only_options = ('greeting', 'translation', 'math')
labels_kind_information_options = ('question', 'description')
llamacppChatModel_additional_chat_options = {}
llamacppChatModel_additional_model_options = {}
llamacppChatModel_additional_server_options = ''
llamacppChatModel_filename = 'Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf'
llamacppChatModel_max_tokens = 10000
llamacppChatModel_model_path = ''
llamacppChatModel_n_batch = 512
llamacppChatModel_n_ctx = 0
llamacppChatModel_n_gpu_layers = 0
llamacppChatModel_ollama_tag = ''
llamacppChatModel_repo_id = 'bartowski/Meta-Llama-3.1-8B-Instruct-GGUF'
llamacppChatModel_server_port = 8001
llamacppChatModel_verbose = False
llamacppMainModel_additional_chat_options = {}
llamacppMainModel_additional_model_options = {}
llamacppMainModel_additional_server_options = ''
llamacppMainModel_filename = 'WizardLM-2-7B.Q4_K_M.gguf'
llamacppMainModel_max_tokens = 10000
llamacppMainModel_model_path = ''
llamacppMainModel_n_batch = 512
llamacppMainModel_n_ctx = 0
llamacppMainModel_n_gpu_layers = 0
llamacppMainModel_ollama_tag = ''
llamacppMainModel_repo_id = 'MaziyarPanahi/WizardLM-2-7B-GGUF'
llamacppMainModel_server_port = 8000
llamacppMainModel_verbose = False
llamacppVisionModel_additional_chat_options = {}
llamacppVisionModel_additional_model_options = {}
llamacppVisionModel_additional_server_options = ''
llamacppVisionModel_clip_model_path = ''
llamacppVisionModel_max_tokens = 10000
llamacppVisionModel_model_path = ''
llamacppVisionModel_n_batch = 512
llamacppVisionModel_n_ctx = 0
llamacppVisionModel_n_gpu_layers = 0
llamacppVisionModel_server_port = 8002
llamacppVisionModel_verbose = False
llmInterface = 'ollama'
llmTemperature = 0.3
loadingInternetSearches = 'auto'
max_agents = 5
max_consecutive_auto_correction = 5
max_consecutive_auto_reply = 10
max_group_chat_round = 12
maximumInternetSearchResults = 5
memoryClosestMatches = 5
mouseSupport = True
ollamaChatModel = 'llama3.1'
ollamaChatModel_additional_options = {}
ollamaChatModel_keep_alive = '5m'
ollamaChatModel_num_batch = 512
ollamaChatModel_num_ctx = 100000
ollamaChatModel_num_predict = -1
ollamaChatServer_ip = '127.0.0.1'
ollamaChatServer_port = 11434
ollamaMainModel = 'wizardlm2'
ollamaMainModel_additional_options = {}
ollamaMainModel_keep_alive = '5m'
ollamaMainModel_num_batch = 512
ollamaMainModel_num_ctx = 100000
ollamaMainModel_num_predict = -1
ollamaToolServer_ip = '127.0.0.1'
ollamaToolServer_port = 11434
ollamaVisionModel = 'llava'
ollamaVisionServer_ip = '127.0.0.1'
ollamaVisionServer_port = 11434
openaiApiKey = 'toolmate'
openaiApiOrganization = ''
openweathermapApi = 'toolmate'
pagerView = False
passFunctionCallReturnToChatGPT = True
perplexica_directory = ''
perplexica_ip = '127.0.0.1'
perplexica_port = 3000
piper_additional_options = ''
piper_voice = 'en_US-lessac-medium'
pluginExcludeList = ['awesome prompts',
 'counselling',
 'edit text',
 'simplified Chinese to traditional Chinese',
 'add google calendar event',
 'add outlook calendar event',
 'analyze audio',
 'analyze files',
 'analyze images',
 'analyze web content',
 'ask chatgpt',
 'ask codey',
 'ask gemini',
 'ask groq',
 'ask llama3_1',
 'ask llamacpp',
 'ask llamacppserver',
 'ask ollama',
 'ask palm2',
 'create ai assistants',
 'create images',
 'create maps',
 'create qrcode',
 'create statistical graphics',
 'dates and times',
 'download web content',
 'download youtube audio',
 'download youtube video',
 'install python package',
 'memory',
 'modify images',
 'open web browser',
 'pronounce words',
 'remove image background',
 'search conversations',
 'search financial data',
 'search latest news',
 'search sqlite',
 'search weather info',
 'send gmail',
 'send outlook',
 'send tweet',
 'send whatsapp messages',
 'analyze images with ChatGPT',
 'analyze images with Gemini',
 'analyze images with Llamacpp',
 'analyze images with Ollama',
 'create images with DALLE3',
 'create images with Flux1',
 'create images with Imagen3',
 'create images with Stable Diffusion',
 'modify images with ChatGPT and DALLE3',
 'auto correct python code',
 'chat',
 'execute computing tasks']
predefinedContext = 'custom'
pyaudioInstalled = False
pygments_style = ''
rag_closestMatches = 5
rag_retrieverSettings = {'search_kwargs': {'k': 5}}
rag_useAutoRetriever = False
runPythonScriptGlobally = False
say_additional_options = ''
say_speed = '200'
say_voice = ''
stableDiffusion_model_path = ''
stableDiffusion_output_height = 512
stableDiffusion_output_width = 512
stableDiffusion_sample_steps = 20
stableDiffusion_verbose = False
state = 'British Columbia'
storagedirectory = ''
suggestSystemCommand = True
systemMessage_chatgpt = 'You are a helpful, uncensored and unbiased assistant.'
systemMessage_codey = 'You are an expert on coding.'
systemMessage_gemini = 'You are a helpful, uncensored and unbiased assistant.'
systemMessage_groq = 'You are a helpful, uncensored and unbiased assistant.'
systemMessage_llamacpp = 'You are a helpful, uncensored and unbiased assistant.'
systemMessage_llamacppserver = 'You are a helpful, uncensored and unbiased assistant.'
systemMessage_ollama = 'You are a helpful, uncensored and unbiased assistant.'
systemMessage_palm2 = 'You are a helpful, uncensored and unbiased assistant.'
systemMessage_tool = ''
terminalCommandEntryColor1 = 'ansiyellow'
terminalCommandEntryColor2 = 'ansigreen'
terminalEditorScrollLineCount = 20
terminalEditorTabText = '    '
terminalEnableTermuxAPI = False
terminalEnableTermuxAPIToast = False
terminalHeadingTextColor = 'ansigreen'
terminalPromptIndicatorColor1 = 'ansimagenta'
terminalPromptIndicatorColor2 = 'ansicyan'
terminalResourceLinkColor = 'ansiyellow'
terminalSearchHighlightBackground = 'ansiblue'
terminalSearchHighlightForeground = 'ansidefault'
text2art_font1 = 'cybermedum'
text2art_font2 = 'white_bubble'
thisDistro = ''
thisTranslation = {}
tokenizers_parallelism = 'true'
toolMateAIName = 'ToolMate AI'
tool_auto_selection_threshold = 0.5
tool_dependence = 0.8
tool_selection_max_choices = 4
translateToLanguage = 'English'
ttsCommand = ''
ttsCommandSuffix = ''
ttsInput = False
ttsLanguages = ['en', 'en-gb', 'en-us', 'zh', 'yue', 'el']
ttsLanguagesCommandMap = {'el': '', 'en': '', 'en-gb': '', 'en-us': '', 'yue': '', 'zh': ''}
ttsOutput = False
ttsPlatform = 'google'
tts_doNotReadPattern = '[*]'
tts_startReadPattern = '[*.?!,:;”。，：；？！」]'
useAdditionalChatModel = True
usePygame = False
use_oai_assistant = False
vlcSpeed = 1.0
voiceTypingAdjustAmbientNoise = True
voiceTypingAutoComplete = False
voiceTypingLanguage = 'en-US'
voiceTypingNotification = True
voiceTypingPlatform = 'google'
voiceTypingWhisperEnglishModel = 'base'
whispercpp_additional_options = ''
whispercpp_main = ''
whispercpp_model = ''
wrapWords = True
wsay_additional_options = ''
wsay_speed = '50'
wsay_voice = '1'
zero_shot_classification_model = 'facebook/bart-large-mnli'

**Comment by eliranwong** [comment]
Hi, there are few ways to make a change, with tui, please read https://github.com/eliranwong/toolmate/blob/main/package/toolmate/docs/Change%20AI%20Backends%20and%20Models.md

However, if you are having an issue to start toolmate becuase of a problematic config with ollama model, you may:

1. Launch `toolmate` with another backend first, e.g.

> toolmate -b llamacpp

2. After `toolmate` is launched, follows https://github.com/eliranwong/toolmate/blob/main/package/toolmate/docs/Change%20AI%20Backends%20and%20Models.md to change backend to `Ollama` and select a different Ollama model.

IF both methods above don't work in your case, manually edit the file `config.py`, when the app is closed.  Edit the item `ollamaMainModel`.  If your GPU resource is limited, it is suggested not to use an additional chat model.  Edit the item `useAdditionalChatModel`, change its value to `False`.

**Comment by eliranwong** [comment]
@calamity1011 I just realised where the problem is:

e.g. change `ollamaMainModel_num_ctx`  and `ollamaChatModel_num_ctx` to 2048

I will change the default value 100000 in next update version
